# Generated by Django 5.0.2 on 2024-08-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('nova', 'Nova'), ('antiga', 'Antiga')], default='antiga', max_length=200, verbose_name='Categoria Laboral'),
        ),
    ]
