# Generated by Django 4.2.13 on 2024-07-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBulkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='employees/bulkupload/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('activo', 'Activo'), ('pre-reformado', 'Pré-Reformado'), ('licenciado', 'Licenciado'), ('reformado', 'Reformado')], default='activo', max_length=100, verbose_name='situacao')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('incluso', 'Incluso')], default='activo', max_length=100, verbose_name='estado')),
                ('origem', models.CharField(choices=[('primavera', 'Primavera'), ('incluso', 'Incluso')], default='incluso', max_length=100, verbose_name='origem')),
                ('personnel_number', models.CharField(max_length=200, null=True, unique=True, verbose_name='Número do BI')),
                ('data_de_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão do BI')),
                ('data_de_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade do BI')),
                ('numero_mecanografico', models.CharField(max_length=200, null=True, unique=True, verbose_name='Número Mecanográfico')),
                ('firstname', models.CharField(max_length=200, verbose_name='Primeiro Nome')),
                ('surname', models.CharField(max_length=200, verbose_name='SobreNome')),
                ('idade', models.CharField(max_length=200, verbose_name='Idade')),
                ('correio_electronico', models.CharField(max_length=200, null=True, verbose_name='Correio Electrónico')),
                ('gender', models.CharField(choices=[('masculino', 'Мasculino'), ('femenino', 'Femenino')], default='masculino', max_length=10, verbose_name='Genero')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('provincia_residencia', models.CharField(choices=[('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bié', 'Bié'), ('Cabinda', 'Cabinda'), ('Cuando Cubango', 'Cuando Cubango'), ('Cuanza Norte', 'Cuanza Norte'), ('Cuanza Sul', 'Cuanza Sul'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huíla', 'Huíla'), ('Luanda', 'Luanda'), ('Lunda Norte', 'Lunda Norte'), ('Lunda Sul', 'Lunda Sul'), ('Malanje', 'Malanje'), ('Moxico', 'Moxico'), ('Namibe', 'Namibe'), ('Uíge', 'Uíge'), ('Zaire', 'Zaire')], default='Luanda', max_length=30, verbose_name='Província de Residência')),
                ('provincia_nascimento', models.CharField(choices=[('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bié', 'Bié'), ('Cabinda', 'Cabinda'), ('Cuando Cubango', 'Cuando Cubango'), ('Cuanza Norte', 'Cuanza Norte'), ('Cuanza Sul', 'Cuanza Sul'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huíla', 'Huíla'), ('Luanda', 'Luanda'), ('Lunda Norte', 'Lunda Norte'), ('Lunda Sul', 'Lunda Sul'), ('Malanje', 'Malanje'), ('Moxico', 'Moxico'), ('Namibe', 'Namibe'), ('Uíge', 'Uíge'), ('Zaire', 'Zaire')], default='Luanda', max_length=30, verbose_name='Província de Nascimento')),
                ('naturalidade', models.CharField(max_length=30, null=True, verbose_name='Naturalidade')),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], default='solteiro', max_length=10, verbose_name='Estado Cívil')),
                ('localidade', models.CharField(max_length=200, null=True, verbose_name='Localidade')),
                ('morada', models.CharField(max_length=200, null=True, verbose_name='Morada')),
                ('numero_dependentes', models.CharField(max_length=200, null=True, verbose_name='Número Dependentes')),
                ('telefone', models.CharField(max_length=9, null=True, verbose_name='Telefone')),
                ('habilitacao', models.CharField(max_length=600, null=True, verbose_name='Habilitação')),
                ('area_de_formacao', models.CharField(max_length=600, null=True, verbose_name='Área de Formação')),
                ('vencimento_mensal', models.CharField(max_length=9, null=True, verbose_name='Vencimento')),
                ('estabelecimento', models.CharField(max_length=200, null=True, verbose_name='estabelecimento')),
                ('reformado', models.CharField(choices=[('activo', 'Activo'), ('pre-reformado', 'Pré-Reformado'), ('licenciado', 'Licenciado'), ('reformado', 'Reformado')], default='activo', max_length=100, verbose_name='estado')),
                ('data_de_admissao', models.DateField(null=True, verbose_name='Data de Demissão')),
                ('vinculo_professor', models.CharField(max_length=200, null=True, verbose_name='Vinculo Professor')),
                ('curso_ministrado', models.CharField(max_length=200, null=True, verbose_name='Curso Ministrado')),
                ('regime_trabalho', models.CharField(max_length=200, null=True, verbose_name='Regime Trabalho')),
                ('vinculo_administrativo', models.CharField(max_length=200, null=True, verbose_name='Vinculo Administrativo')),
                ('data_de_admissao_administrativo', models.DateField(blank=True, null=True, verbose_name='Data de Admissão Administrativo')),
                ('direccao_administrativo', models.CharField(blank=True, max_length=600, null=True, verbose_name='Direção de Alocação Administrativo')),
                ('categoria_laboral_administrativo', models.CharField(blank=True, max_length=600, null=True, verbose_name='Categoria')),
                ('funcao_chefia_administrativo', models.CharField(blank=True, max_length=600, null=True, verbose_name='Função de Chefia Administrativo')),
                ('vencimento_mensal_administrativo', models.CharField(max_length=9, null=True, verbose_name='Vencimento Administrativo')),
                ('habilitacao_administrativo', models.CharField(max_length=600, null=True, verbose_name='Habilitação')),
                ('area_de_formacao_administrativo', models.CharField(max_length=600, null=True, verbose_name='Área de Formação')),
                ('regime_trabalho_administrativo', models.CharField(max_length=200, null=True, verbose_name='Regime Trabalho Administrativo')),
                ('profissao', models.CharField(max_length=600, null=True, verbose_name='Profissão')),
                ('tipo_contrato', models.CharField(max_length=600, null=True, verbose_name='Tipo de Contrato')),
                ('tipo_pessoal', models.CharField(max_length=600, null=True, verbose_name='Tipo de Pessoal')),
                ('motivo_admissao', models.CharField(max_length=600, null=True, verbose_name='Motivo Admissão')),
                ('data_de_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('motivo_demissao', models.CharField(max_length=600, null=True, verbose_name='Motivo Demissao')),
                ('data_fim_contrato', models.DateField(blank=True, null=True, verbose_name='Data de Fim de Contrato')),
                ('anos_trabalho', models.CharField(max_length=600, null=True, verbose_name='Anos de Trabalho')),
                ('cargo', models.CharField(max_length=600, null=True, verbose_name='Cargo / Função')),
                ('situacao_contrato', models.CharField(max_length=600, null=True, verbose_name='Efectivo / Contratado')),
                ('carga_horaria_diurna', models.CharField(max_length=600, null=True, verbose_name='Carga Horária Diurna')),
                ('carga_horaria_nocturna', models.CharField(max_length=600, null=True, verbose_name='Carga Horária Nocturna')),
                ('valor_aula_diurna', models.CharField(max_length=600, null=True, verbose_name='Valor Aula Diurna')),
                ('valor_aula_nocturna', models.CharField(max_length=600, null=True, verbose_name='Valor Aula Nocturna')),
                ('aula_diurna', models.CharField(max_length=600, null=True, verbose_name='Aula Diurna')),
                ('aula_nocturna', models.CharField(max_length=600, null=True, verbose_name='Aula Diurna')),
                ('honorario_total', models.CharField(max_length=600, null=True, verbose_name='Honorário Total')),
                ('photo', models.ImageField(blank=True, upload_to='employees/photos/', verbose_name='Foto')),
                ('estado_objecto', models.CharField(choices=[('activo', 'Activo'), ('eliminado', 'Eliminado')], default='activo', max_length=200, verbose_name='estado objecto')),
                ('numero_seguranca_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero de Segurança Social')),
                ('estado_pv', models.CharField(choices=[('pendente', 'Pendente'), ('feito', 'Feito'), ('faltoso', 'Faltoso')], default='pendente', max_length=200, verbose_name='estado prova vida')),
                ('novo_numero_mecanografico', models.CharField(max_length=200, null=True, unique=True, verbose_name='Novo Número Mecanográfico')),
                ('estado_origem', models.CharField(choices=[('pendente', 'Pendente'), ('feito', 'Feito'), ('faltoso', 'Faltoso')], default='inclusao', max_length=200, verbose_name='estado de origem')),
                ('categoria_laboral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corecode.categoria', verbose_name='Categoria')),
                ('categoria_nova', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corecode.categorianova', verbose_name='Categoria Nova')),
                ('direccao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.direcaoalocacao', verbose_name='Direção de Alocação')),
                ('funcao_chefia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corecode.funcaochefia', verbose_name='funcao de chefia')),
                ('nacionalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corecode.citizenship', verbose_name='Nacionalidade')),
            ],
            options={
                'ordering': ['personnel_number', 'firstname', 'surname'],
            },
        ),
    ]
