# Generated by Django 5.0.3 on 2024-07-29 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
        ('employees', '0003_alter_employee_categoria_laboral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='categoria_laboral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corecode.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='categoria_laboral_administrativo',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='direccao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.direcaoalocacao', verbose_name='Direção de Alocação'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='direccao_administrativo',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Direção de Alocação Administrativo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='funcao_chefia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corecode.funcaochefia', verbose_name='funcao de chefia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='funcao_chefia_administrativo',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Função de Chefia Administrativo'),
        ),
    ]
