# Generated by Django 5.0.3 on 2024-08-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_categoria_laboral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='anos_trabalho',
            field=models.CharField(max_length=2000, null=True, verbose_name='Anos de Trabalho'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='area_de_formacao',
            field=models.CharField(max_length=2000, null=True, verbose_name='Área de Formação'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='area_de_formacao_administrativo',
            field=models.CharField(max_length=2000, null=True, verbose_name='Área de Formação'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='aula_diurna',
            field=models.CharField(max_length=2000, null=True, verbose_name='Aula Diurna'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='aula_nocturna',
            field=models.CharField(max_length=2000, null=True, verbose_name='Aula Diurna'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='carga_horaria_diurna',
            field=models.CharField(max_length=2000, null=True, verbose_name='Carga Horária Diurna'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='carga_horaria_nocturna',
            field=models.CharField(max_length=2000, null=True, verbose_name='Carga Horária Nocturna'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cargo',
            field=models.CharField(max_length=2000, null=True, verbose_name='Cargo / Função'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='categoria_laboral_administrativo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='correio_electronico',
            field=models.CharField(max_length=2000, null=True, verbose_name='Correio Electrónico'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='curso_ministrado',
            field=models.CharField(max_length=2000, null=True, verbose_name='Curso Ministrado'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='direccao_administrativo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='estabelecimento',
            field=models.CharField(max_length=2000, null=True, verbose_name='estabelecimento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=2000, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='funcao_chefia_administrativo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='habilitacao',
            field=models.CharField(max_length=2000, null=True, verbose_name='Habilitação'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='habilitacao_administrativo',
            field=models.CharField(max_length=2000, null=True, verbose_name='Habilitação'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='honorario_total',
            field=models.CharField(max_length=2000, null=True, verbose_name='Honorário Total'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='idade',
            field=models.CharField(max_length=2000, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='localidade',
            field=models.CharField(max_length=2000, null=True, verbose_name='Localidade'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='morada',
            field=models.CharField(max_length=2000, null=True, verbose_name='Morada'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='motivo_admissao',
            field=models.CharField(max_length=2000, null=True, verbose_name='Motivo Admissão'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='motivo_demissao',
            field=models.CharField(max_length=2000, null=True, verbose_name='Motivo Demissao'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='numero_dependentes',
            field=models.CharField(max_length=2000, null=True, verbose_name='Número Dependentes'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='numero_mecanografico',
            field=models.CharField(max_length=2000, null=True, unique=True, verbose_name='Número Mecanográfico'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personnel_number',
            field=models.CharField(max_length=2000, null=True, unique=True, verbose_name='Número do BI'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profissao',
            field=models.CharField(max_length=2000, null=True, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='regime_trabalho',
            field=models.CharField(max_length=2000, null=True, verbose_name='Regime Trabalho'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='regime_trabalho_administrativo',
            field=models.CharField(max_length=2000, null=True, verbose_name='Regime Trabalho Administrativo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='situacao_contrato',
            field=models.CharField(max_length=2000, null=True, verbose_name='Efectivo / Contratado'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=2000, verbose_name='SobreNome'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tipo_contrato',
            field=models.CharField(max_length=2000, null=True, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tipo_pessoal',
            field=models.CharField(max_length=2000, null=True, verbose_name='Tipo de Pessoal'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='valor_aula_diurna',
            field=models.CharField(max_length=2000, null=True, verbose_name='Valor Aula Diurna'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='valor_aula_nocturna',
            field=models.CharField(max_length=2000, null=True, verbose_name='Valor Aula Nocturna'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vinculo_administrativo',
            field=models.CharField(max_length=2000, null=True, verbose_name='Vinculo Administrativo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vinculo_professor',
            field=models.CharField(max_length=2000, null=True, verbose_name='Vinculo Professor'),
        ),
    ]
