# Generated by Django 5.0.3 on 2024-08-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_anos_trabalho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], default='solteiro', max_length=20, verbose_name='Estado Cívil'),
        ),
    ]
