# Generated by Django 5.0.2 on 2024-08-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_estado_civil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='reformado',
        ),
        migrations.AddField(
            model_name='employee',
            name='reforma',
            field=models.CharField(choices=[('reformado', 'Reformado'), ('pré-reforma', 'Pré-reforma'), ('não reformado', 'Não reformado')], default='reformado', max_length=20, verbose_name='Reforma'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tempo_na_empresa',
            field=models.CharField(default='NaN', max_length=50),
        ),
    ]
