# Generated by Django 5.0.2 on 2024-08-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_reformado_employee_reforma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Estabelecimento')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='estabelecimento',
        ),
    ]
