# Generated by Django 5.0.2 on 2024-08-29 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0002_categoria_tipo'),
        ('employees', '0009_alter_employee_nacionalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='categoria_laboral',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='categoria_nova',
        ),
        migrations.AddField(
            model_name='employee',
            name='categoria_laboral_antiga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios_com_categoria_antiga', to='corecode.categoria', verbose_name='Categoria Antiga'),
        ),
        migrations.AddField(
            model_name='employee',
            name='categoria_laboral_nova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios_com_categoria_nova', to='corecode.categoria', verbose_name='Categoria Nova'),
        ),
    ]
