# Generated by Django 4.2.13 on 2024-07-16 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abertura_Prova_Vida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.TextField(max_length=400, null=True, unique=True, verbose_name='Referência')),
                ('estado_actual', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=20, verbose_name='estado')),
                ('data_de_abertura', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Abertura')),
                ('data_de_fim', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Fim')),
                ('data_de_fecho', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de Fecho')),
                ('descricao', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='ProvaVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('concluida', 'Concluida'), ('anulada', 'Anulado')], default='concluida', max_length=10, verbose_name='estado')),
                ('data_prova_vida', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de prova de vida')),
                ('novo_numero_mecanografico', models.CharField(max_length=200, null=True, verbose_name='Novo Número Mecanográfico')),
                ('novo_vencimento', models.CharField(max_length=200, null=True, verbose_name='Novo Vencimento')),
                ('local_prova', models.CharField(max_length=200, null=True, verbose_name='Local')),
                ('observacao', models.CharField(max_length=1000, null=True, verbose_name='observacao')),
                ('abertura_prova_vida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prova_vida.abertura_prova_vida', verbose_name='Abertura Prova de Vida')),
                ('categoria_nova', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corecode.categorianova', verbose_name='Categoria Nova')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='funcionário')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilizador')),
            ],
            options={
                'ordering': ['estado', 'funcionario', 'abertura_prova_vida', 'data_prova_vida'],
            },
        ),
        migrations.AddField(
            model_name='abertura_prova_vida',
            name='provasVida',
            field=models.ManyToManyField(related_name='abertura_prova_vidas', to='prova_vida.provavida'),
        ),
    ]
